import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — Signal to Startup',
  description: 'Terms of Service for Signal to Startup by EntrepAIneur.',
};

export default function TermsPage() {
  return (
    <main className="min-h-screen bg-background text-foreground px-4 py-16">
      <div className="max-w-3xl mx-auto space-y-12">

        {/* Header */}
        <div className="space-y-3 border-b border-border/10 pb-8">
          <p className="text-[10px] font-mono uppercase tracking-widest text-muted">Legal</p>
          <h1 className="text-4xl font-serif italic font-bold">Terms of Service</h1>
          <p className="text-sm text-muted">Last updated: January 1, 2026</p>
        </div>

        {/* Sections */}
        <div className="space-y-10 text-[15px] leading-relaxed">

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">1. Informational Purpose Only</h2>
            <p className="text-muted">
              Signal to Startup is a tool designed to surface market signals and generate
              business ideas using artificial intelligence. All content generated by this
              service — including opportunity analyses, business plans, cost estimates, and
              market assessments — is provided for <strong>informational and educational purposes
              only</strong>.
            </p>
            <p className="text-muted">
              Nothing on this platform constitutes financial advice, legal advice, investment
              advice, or a recommendation to take any specific business action. You should
              consult qualified professionals before making any financial or legal decisions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">2. AI-Generated Content Disclaimer</h2>
            <p className="text-muted">
              Content generated by the AI engine (powered by Google Gemini) reflects the
              model&apos;s interpretation of the input provided. It may contain inaccuracies,
              outdated information, or speculative projections. EntrepAIneur does not warrant
              the accuracy, completeness, or fitness of AI-generated content for any particular
              purpose.
            </p>
            <p className="text-muted">
              AI-generated business ideas are not vetted by financial or legal professionals.
              Use your own judgment and conduct independent research before acting on any
              suggestions.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">3. User Data &amp; Privacy</h2>
            <p className="text-muted">
              By signing in with Google, you authorize us to store your Google profile
              information (name, email address, and profile photo) and your saved opportunities
              and analysis history in Firebase Firestore — a secure, Google-hosted database.
            </p>
            <p className="text-muted">
              Your data is used solely to provide and improve the Signal to Startup experience.
              We do not sell, rent, or share your personal data with third-party advertisers.
              See our <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link> for
              full details on how your data is handled.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">4. Data Deletion</h2>
            <p className="text-muted">
              You may delete individual analyses at any time from the History panel within the
              app. To request full deletion of your account and all associated data, contact us
              at{' '}
              <a href="mailto:support@entrepaineur.com" className="text-primary hover:underline">
                support@entrepaineur.com
              </a>
              . We will process your request within 30 days.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">5. Acceptable Use</h2>
            <p className="text-muted">
              You agree not to use Signal to Startup to generate content that is misleading,
              fraudulent, defamatory, or in violation of any applicable law. You are solely
              responsible for how you use the information generated by this service.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">6. Modifications to the Service</h2>
            <p className="text-muted">
              EntrepAIneur reserves the right to modify, suspend, or discontinue any part of
              Signal to Startup at any time without prior notice. We may update these Terms of
              Service periodically. Continued use of the service after changes are posted
              constitutes acceptance of the revised terms.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">7. Limitation of Liability</h2>
            <p className="text-muted">
              To the fullest extent permitted by law, EntrepAIneur shall not be liable for any
              indirect, incidental, special, consequential, or punitive damages arising from
              your use of or inability to use this service, including any business losses or
              decisions made based on AI-generated content.
            </p>
          </section>

          <section className="space-y-3">
            <h2 className="text-lg font-semibold">8. Contact</h2>
            <p className="text-muted">
              For questions about these Terms, contact us at{' '}
              <a href="mailto:support@entrepaineur.com" className="text-primary hover:underline">
                support@entrepaineur.com
              </a>
              .
            </p>
          </section>

        </div>

        {/* Back link */}
        <div className="border-t border-border/10 pt-8">
          <Link href="/" className="text-xs font-mono uppercase tracking-widest text-muted hover:text-foreground transition-colors">
            ← Back to Signal to Startup
          </Link>
        </div>

      </div>
    </main>
  );
}
